### ISSUE TITLE
Podcast.__init__ Interview About Crossbar.io

### ISSUE THREAD

**Issue by blarghmatey** [BoundlessNotions/podcastinit-meta#2]
@oberstet I would like to produce an interview about Crossbar.io on [Podcast.__init__](https://www.podcastinit.com). If that is something that you are interested in then please email me at tmacey [at] podcastinit [dot] com.

**Comment by goeddea** [comment]
Seems to be quite technical in nature - so that's necessarily something for @oberstet to do. 

I cannot find any information on how many listeners this has, but the fact that they're at #98 by now inspires some trust. No idea who the people interviewed are.

So: Worth a try if the effort is low, e.g. 1-hour interview on the phone.

**Comment by blarghmatey** [comment]
@goeddea that is an accurate representation of the level of effort. The interview is generally an hour long and I provide a list of questions ahead of time for review.

**Comment by oberstet** [comment]
@blarghmatey Ok, cool! Lets do it.
